1 alu
sanassi/vhdl-proj pull request #2
Opened 2024-05-05 19:48 UTC by sanassi

did most of the work for the alu, and started the register bench. will now create another issue for the assembly of the processing unit.
still needs to be added:
- other / better overflow checks
- carry checks (need to add en extra bit and see if it's set to zero)

2024-05-07 21:21 UTC, Trucjdh requested changes
Only checked `alu.vhd` and `alu_tb.vhd`.
 If you agree with my review I will apply it as the same time I refactor some code in `alu.vhd` and add  carry checking etc

2024-05-07 21:21 UTC, Trucjdh commented on src/alu.vhd
We should stick to one convention when declaring std_logic_vector etc : either *downto* or *to*. I think it would be best to use the *downto* convention (little endian system) so we must change every occurences of `std_logic_vector(Y to X);` to `std_logic_vector(X downto Y);`

2024-05-07 21:21 UTC, Trucjdh commented on src/alu_tb.vhd
I think it would be better for the architecture to put tests bench files in a dedicated directory instead of `src`

2024-05-07 21:21 UTC, Trucjdh commented on src/alu.vhd
>      signal temp_sum  : std_logic_vector(0 to 32) := (others => '0');
`temp_sum` is not used anymore (the `carry` variable too but carry are not checked yet)

2024-05-07 21:29 UTC, sanassi commented on src/alu.vhd
>      signal temp_sum  : std_logic_vector(0 to 32) := (others => '0');
ye reste du check sur les carry que j'avais commencé à faire, mai qui faisait une erreur fatale pendant les tests. je pense voir d'ù ça venait mais flemme de réecrire ce soir 🤠

2024-05-07 21:31 UTC, Trucjdh commented on src/alu.vhd
>      signal temp_sum  : std_logic_vector(0 to 32) := (others => '0');
speek english please I dont understnad

2024-05-07 21:33 UTC, sanassi commented on src/alu.vhd
>      signal temp_sum  : std_logic_vector(0 to 32) := (others => '0');
me no hablo ingles me dominican

2024-05-07 21:36 UTC, sanassi commented on src/alu.vhd
>      signal temp_sum  : std_logic_vector(0 to 32) := (others => '0');
sure clara we'll speak in english from now on ..
![Uploading mario-luigi.gif…]()

2024-05-15 09:30 UTC, Trucjdh approved these changes

2024-05-15 10:37 UTC, merged